config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :rosters
  resources :courses
  resources :offerings
  resources :charges, only: [:new, :create]
  #resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_resets, only: [ :new, :create]
  get '/password_resets/edit' => 'password_resets#edit', as: :edit_password_reset
  put '/password_resets/' => 'password_resets#update', as: :password_reset

  get '/home', to: 'static_pages#home'
  get '/courses', to: 'static_pages#courses'
  
  get '/admin_active', to: 'admin_pages#active_courses'
  get '/admin_add', to: 'admin_pages#add_course'
  get '/admin_edit', to: 'admin_pages#edit_course'
  get '/admin_delete', to: 'admin_pages#delete_course'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'static_pages/home'
  get 'static_pages/courses'
  get 'static_pages/contact'

  get 'users/new'
  get 'users/edit'

  get 'admin_pages/active_courses'
  get 'admin_pages/add_course'
  get 'admin_pages/delete_course'
  get 'admin_pages/edit_course'

  #get    '/contact',   to: 'contacts#new'
  #post   '/contact',   to: 'contacts#create'
  match '/contact', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  root 'static_pages#home'
end

app/models/offering.rb
class Offering < ApplicationRecord
  belongs_to :course
  has_many :rosters, dependent: :destroy
  has_many :users, through: :rosters

  validates :coursePrice, presence: true, numericality: true, format: { with: /\A\d{1,4}(\.\d{0,2})?\z/ }
end

app/controllers/offerings_controller.rb
class OfferingsController < ApplicationController
  def offering_params
    params.require(:offering).permit(:courseDate, :courseTime, :courseNotes, :coursePrice, :course_id)
  end

  def index
    @offerings = Offering.all
  end

  def new
    # default: render 'new' template
    @course_id = params[:course_id]
  end

  def create
    @offering = Offering.new(offering_params)
    # @offering.courseDate = (@offering.courseDate.to_time - 6.hours).to_datetime

    if @offering.save
      flash[:success] = "Clase agregada exitosamente '#{@offering.course_id}' on '#{@offering.courseDate}'"
      redirect_to course_path(@offering.course_id)
    end
  end

  def show
    @offering = Offering.find(params[:id])
  end

  def edit
    @offering = Offering.find(params[:id])
  end

  def update
    @offering = Offering.find(params[:id])
    if @offering.update_attributes(offering_params)
      redirect_to course_path(@offering.course_id)
    else
      render 'edit'
    end
  end

  def destroy
    @offering = Offering.find(params[:id])
    @offering.destroy
    flash[:notice] = "Clase '#{@offering.courseDate}' borrada."
    redirect_to course_path(@offering.course_id)
  end
end

app/helpers/offerings_helper.rb
module OfferingsHelper
end

app/views/offerings/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <div>
    <span class="h3">Editar los detalles de la clase:</span>
  </div>
  <br>
  <%= form_for @offering do |f| %>
      <div class="form-group">
        <%= f.label :course_id, "Curso #:" %>
        <%= f.text_field :course_id, class: "form-control", readonly: true %>
      </div>
      <div class="form-group">
        <%= f.label :courseDate, "Fecha de clase:" %>
        <%= f.date_field :courseDate, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :courseTime, "Hora de clase:" %>
        <%= f.time_field :courseTime, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :coursePrice, "Precio de la clase:" %>
        <div class="input-group">
          <span class="input-group-addon">$</span>
          <%= f.text_field :coursePrice, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :courseNotes, "Otras Notas:" %>
        <%= f.text_field :courseNotes, class: "form-control" %>
      </div>
      <%= f.submit "Guardar", class: "btn btn-default" %>
  <% end %>
</div>

app/views/offerings/index.html.erb
<h1>Offerings</h1>

<table id="offerings">
  <thead>
  <tr>
    <th>Offering ID</th>
    <th>Date</th>
    <th>Notes</th>
    <th>Price</th>
    <th>Course ID</th>
  </tr>
  </thead>
  <tbody>
  <% @offerings.each do |offering| %>
      <tr>
        <td><%= offering.id %></td>
        <td><%= offering.courseDate  %></td>
        <td><%= offering.courseNotes %></td>
        <td><%= offering.coursePrice %></td>
        <td><%= offering.course_id   %></td>
        <td><%= link_to "Details", offering_path(offering) %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Add new offering', new_offering_path %>

app/views/offerings/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div>
    <span class="h3">Ingrese nuevos detalles de la clase:</span>
  </div>
  <br>
  <%= form_for Offering.new do |f| %>
      <div class="form-group">
        <%= f.label :course_id, "Clase #:" %>
        <%= f.text_field :course_id, class: "form-control", readonly: true, value: @course_id %>
      </div>
      <div class="form-group">
        <%= f.label :courseDate, "Fecha:" %>
        <%= f.date_field :courseDate, class: "form-control", value: Date.today %>
      </div>
      <div class="form-group">
        <%= f.label :courseTime, "Hora:" %>
        <%= f.time_field :courseTime, class: "form-control", value: Time.now.strftime("%H:%M") %>
      </div>
      <div class="form-group">
        <%= f.label :coursePrice, "Precio de la clase:" %>
        <div class="input-group">
          <span class="input-group-addon">$</span>
          <%= f.text_field :coursePrice, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :courseNotes, "Otras notas:" %>
        <%= f.text_field :courseNotes, class: "form-control" %>
      </div>
      <%= f.submit "Enviar", class: "btn btn-default" %>
  <% end %>
</div>

app/views/offerings/show.html.erb
<h2>Offering <%= @offering.id %></h2>

<ul id="details">
  <li>Course ID: <%= @offering.course_id %></li>
  <li>Date: <%= @offering.courseDate %></li>
  <li>Price: <%= @offering.coursePrice %></li>
  <li>Notes: <%= @offering.courseNotes %></li>
</ul>

<%= button_to 'Delete', offering_path(@offering), :method => :delete, :confirm => 'Are you sure?' %>
<%=link_to 'Back to offerings', offerings_path %> 