config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :rosters
  resources :courses
  resources :offerings
  resources :charges, only: [:new, :create]
  #resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_resets, only: [ :new, :create]
  get '/password_resets/edit' => 'password_resets#edit', as: :edit_password_reset
  put '/password_resets/' => 'password_resets#update', as: :password_reset

  get '/home', to: 'static_pages#home'
  get '/courses', to: 'static_pages#courses'
  
  get '/admin_active', to: 'admin_pages#active_courses'
  get '/admin_add', to: 'admin_pages#add_course'
  get '/admin_edit', to: 'admin_pages#edit_course'
  get '/admin_delete', to: 'admin_pages#delete_course'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'static_pages/home'
  get 'static_pages/courses'
  get 'static_pages/contact'

  get 'users/new'
  get 'users/edit'

  get 'admin_pages/active_courses'
  get 'admin_pages/add_course'
  get 'admin_pages/delete_course'
  get 'admin_pages/edit_course'

  #get    '/contact',   to: 'contacts#new'
  #post   '/contact',   to: 'contacts#create'
  match '/contact', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  root 'static_pages#home'
end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
  include SessionsHelper
  include CoursesHelper

  before_action :check_admin

  # ROUTING
  def active_courses
    @courses = Course.all
  end

  def add_course
  end

  def edit_course
  end

  def delete_course
  end

  # END ROUTING

  private

  def check_admin
    redirect_to home_path unless admin?
  end
end

app/views/admin_pages/active_courses.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>

<div id="Active">
  <h3>Cursos Activos</h3>
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Nombre del Curso</th>
        <th>Descripción</th>
      </tr>
    </thead>
    <tbody>
      <% @courses.each do |course| %>
          <tr>
            <td><%= course.id %></td>
            <td><%= course.courseName %></td>
            <td><%= course.courseDesc %></td>
          </tr>
      <% end %>
    </tbody>

  </table>
  
</body>
</html> 

app/views/admin_pages/add_course.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>
    
<!-- OPTION: the tabs can be changed into static pages for organization purposes -->
<div class="tab">
  <button class="tablinks"><%= link_to "Active Courses", admin_active_path, class: "prettyLink" %></button>
  <button class="tablinks active"><%= link_to "Add Course", admin_add_path, class: "prettyLink" %></button>
  <button class="tablinks"><%= link_to "Edit Course", admin_edit_path, class: "prettyLink" %></button>
  <button class="tablinks"><%= link_to "Delete Course", admin_delete_path, class: "prettyLink" %></button>
</div>

<div id="Add" class="tabcontent">
  <h3>Add Course</h3>
  <%= form_for Course.new do |f| %>
    <%= f.label :courseName %>
    <%= f.text_field :courseName %>

    <%= f.label :courseDesc %>
    <%= f.text_field :courseDesc %>
 
    <br><%= f.submit "Create Course", class: "btn btn-primary" %>
  <% end %>
  
  <h3>Add Offering</h3>
  <%= form_for Offering.new do |f| %>
    <%= f.label :course_id %>
    <%= f.text_field :course_id %>
  
    <%= f.label :courseDate %>
    <%= f.text_field :courseDate %>

    <%= f.label :courseNotes %>
    <%= f.text_field :courseNotes %>
    
    <%= f.label :coursePrice %>
    <%= f.text_field :coursePrice %>

    <br><%= f.submit "Create Offering", class: "btn btn-primary" %>
  <% end %>
</div>

</body>
</html> 

app/views/admin_pages/delete_course.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>
    
<!-- OPTION: the tabs can be changed into static pages for organization purposes -->
<div class="tab">
  <button class="tablinks"><%= link_to "Active Courses", admin_active_path, class: "prettyLink" %></button>
  <button class="tablinks"><%= link_to "Add Course", admin_add_path, class: "prettyLink" %></button>
  <button class="tablinks"><%= link_to "Edit Course", admin_edit_path, class: "prettyLink" %></button>
  <button class="tablinks active"><%= link_to "Delete Course", admin_delete_path, class: "prettyLink" %></button>
</div>

<div id="Delete" class="tabcontent">
  <h3>Delete Page</h3>
  <p>Delete existing course / course offering (?)</p>
</div>

</body>
</html> 

app/views/admin_pages/edit_course.html.erb
<!DOCTYPE html>
<html>
<head></head>
<body>
    
<!-- OPTION: the tabs can be changed into static pages for organization purposes -->
<div class="tab">
  <button class="tablinks"><%= link_to "Active Courses", admin_active_path, class: "prettyLink" %></button>
  <button class="tablinks"><%= link_to "Add Course", admin_add_path, class: "prettyLink" %></button>
  <button class="tablinks active"><%= link_to "Edit Course", admin_edit_path, class: "prettyLink" %></button>
  <button class="tablinks"><%= link_to "Delete Course", admin_delete_path, class: "prettyLink" %></button>
</div>

<div id="Edit" class="tabcontent">
  <h3>Edit Page</h3>
  <p>Edit existing courses or edit an offering (?)</p>
</div>

</body>
</html> 