config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :rosters
  resources :courses
  resources :offerings
  resources :charges, only: [:new, :create]
  #resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_resets, only: [ :new, :create]
  get '/password_resets/edit' => 'password_resets#edit', as: :edit_password_reset
  put '/password_resets/' => 'password_resets#update', as: :password_reset

  get '/home', to: 'static_pages#home'
  get '/courses', to: 'static_pages#courses'
  
  get '/admin_active', to: 'admin_pages#active_courses'
  get '/admin_add', to: 'admin_pages#add_course'
  get '/admin_edit', to: 'admin_pages#edit_course'
  get '/admin_delete', to: 'admin_pages#delete_course'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'static_pages/home'
  get 'static_pages/courses'
  get 'static_pages/contact'

  get 'users/new'
  get 'users/edit'

  get 'admin_pages/active_courses'
  get 'admin_pages/add_course'
  get 'admin_pages/delete_course'
  get 'admin_pages/edit_course'

  #get    '/contact',   to: 'contacts#new'
  #post   '/contact',   to: 'contacts#create'
  match '/contact', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  root 'static_pages#home'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  public
  def index
    @courses = Course.all
  end

  def new
    # default: render 'new' template
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:success] = "Curso creado - '#{@course.courseName}'"
      redirect_to @course
    end
  end

  def show
    @course = Course.find(params[:id])
    @offerings = @course.offerings
    if session[:user_id]
      @registered_offering_ids = Roster.where(user_id: session[:user_id], offering_id: @offerings).pluck(:offering_id)
      print @registered_offering_ids
    end
    
    @users = User.all
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(course_params)
      redirect_to course_path(@course)
    else
      render 'edit'
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    flash[:notice] = "Curso '#{@course.courseName}' borrado."
    redirect_to courses_path
  end

  private
  def course_params
    params.require(:course).permit(:courseName, :courseDesc, :thumbnail)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/edit.html.erb
<div>
  <span class="h3">Editar los detalles del curso:</span>
</div>
<br>

<%= form_for @course do |f| %>
    <div class="form-group">
      <%= f.label :courseName, "Nombre del curso:" %>
      <%= f.text_field :courseName, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :courseDesc, "Breve descripción:" %>
      <%= f.text_area :courseDesc, class: "form-control", rows: '4' %>
    </div>
    <div class="form-group">
      <%= f.label :thumbnail, "Thumbnail image" %>
      <%= f.file_field :thumbnail %>
    </div>

    <%= f.submit "Guardar", class: "btn btn-default" %>
<% end %>

app/views/courses/index.html.erb
<div>
  <span class="h1">Cursos</span>
</div>
<div class="course-list">
  <% @courses.each_with_index do |course, i| %>
      <%= link_to course_path(course), class: 'btn btn-default btn-lg btn-course', role: 'button' do %>
          <div class="media">
            <% if i%2==0 %>
                <div class="media-left">
                  <%= image_tag(course.thumbnail? ? course.thumbnail.url : 'blank.png', alt: 'Thumbnail') %>
                </div>
            <% else %>
                <div class="media-left border">
                </div>
            <% end %>
            <div class="media-body">
              <div class="h2 media-heading"><%= course.courseName %></div>
              <%= course.courseDesc %>
            </div>
            <% if i%2==0 %>
                <div class="media-right border">
                </div>
            <% else %>
                <div class="media-right">
                  <%= image_tag(course.thumbnail? ? course.thumbnail.url : 'blank.png', alt: 'Thumbnail') %>
                </div>
            <% end %>
          </div>
      <% end %>

  <% end %>

  <% if admin? %>
      <%= link_to new_course_path, class: 'btn btn-default btn-primary btn-lg', role: 'button' do %>
          <span>Agregar curso nuevo</span>
      <% end %>
  <% end %>
</div>

app/views/courses/new.html.erb
<div>
  <span class="h3">Ingrese nuevos detalles del curso:</span>
</div>
<br>

<%= form_for Course.new do |f| %>
    <div class="form-group">
      <%= f.label :courseName, "Nombre del curso:" %>
      <%= f.text_field :courseName, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :courseDesc, "Descripción de la curso:" %>
      <%= f.text_area :courseDesc, class: "form-control", rows: 4 %>
    </div>
    <div class="form-group">
      <%= f.label :thumbnail, "Thumbnail image" %>
      <%= f.file_field :thumbnail %>
    </div>

    <%= f.submit "Guardar", class: "btn btn-default" %>
<% end %>

app/views/courses/show.html.erb
<div class="media course-header">
  <% if @course.thumbnail? %>
      <div class="media-left">
        <%= image_tag(@course.thumbnail.url, alt: 'Thumbnail') %>
      </div>
  <% end %>
  <div class="media-body">
    <div class="media-heading">
      <span class="h2"><%= @course.courseName %></span>
      &nbsp;
      <% if admin? %>
          <%= link_to "Editar Curso", edit_course_path(@course) %>
          |
          <%= link_to "Eliminar Curso", @course, method: :delete, data: {confirm: "¿Seguro que quieres eliminar esta curso?"} %>
      <% end %></div>
    <span class="h2"><small><%= @course.courseDesc %></small></span>
  </div>
</div>
<br>
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">Clases</div>

  <table id="offerings" class="table">
    <thead>
    <tr>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Notas</th>
      <th>Precio</th>
      <th>
        <% if admin? %>
            Admin
        <% else %>
            Registracion
        <% end %>
      </th>
    </tr>
    </thead>
    <tbody>
    <% @offerings.each do |offering| %>
        <tr>
          <td><%= offering.courseDate.strftime("%D") %></td>
          <td><%= offering.courseTime.strftime("%-I:%M %p") %></td>
          <td><%= offering.courseNotes %></td>
          <td><%= number_to_currency(offering.coursePrice) %></td>
          <td>
            <% if admin? %>
                <%= link_to "Editar clase", edit_offering_path(offering) %>
                |
                <%= link_to "Eliminar clase", offering, method: :delete, data: {confirm: "¿Seguro que quieres eliminar esta ofrenda?"} %>
            <% elsif session[:user_id] %>
                <% if @registered_offering_ids.include? offering.id %>
                    Te has registrado para esta ofrenda de curso.
                <% else %>
                    <%= form_tag charges_path do %>
                        ¡Pulse aquí para registrarse y pagar!
                        <input type="hidden" name="amount" value="<%= offering.coursePrice*100 %>">
                        <input type="hidden" name="offering_id" value="<%= offering.id %>">
                        <input type="hidden" name="description" value="<%= @course.courseName %> (<%= offering.courseDate.strftime("%D") %> @ <%= offering.courseTime.strftime("%-I:%M %p") %>)">
                        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                                data-description="<%= @course.courseName %> (<%= offering.courseDate.strftime("%D") %> @ <%= offering.courseTime.strftime("%-I:%M %p") %>)"
                                data-amount="<%= offering.coursePrice*100 %>"
                                data-locale="auto"></script>
                    <% end %>
                      <!--<%= link_to "¡Pulse aquí para registrarse!", rosters_path(roster: {user_id: session[:user_id], offering_id: offering.id}), method: :post %>-->
                <% end %>
            <% else %>
                ¡Inicia sesión para registrarte!
            <% end %>
          </td>
        </tr>
    <% end %>
    </tbody>
    <% if admin? %>
        <tfoot>
        <tr>
          <td colspan="5" align="center">
            <%= link_to "Agregar Clase", new_offering_path(course_id: @course), class: 'btn btn-default btn-primary', role: 'button' %>
          </td>
        </tr>
        </tfoot>
    <% end %>
  </table>
</div>