config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :rosters
  resources :courses
  resources :offerings
  resources :charges, only: [:new, :create]
  #resources :password_resets, only: [:new, :create, :edit, :update]
  resources :password_resets, only: [ :new, :create]
  get '/password_resets/edit' => 'password_resets#edit', as: :edit_password_reset
  put '/password_resets/' => 'password_resets#update', as: :password_reset

  get '/home', to: 'static_pages#home'
  get '/courses', to: 'static_pages#courses'
  
  get '/admin_active', to: 'admin_pages#active_courses'
  get '/admin_add', to: 'admin_pages#add_course'
  get '/admin_edit', to: 'admin_pages#edit_course'
  get '/admin_delete', to: 'admin_pages#delete_course'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'static_pages/home'
  get 'static_pages/courses'
  get 'static_pages/contact'

  get 'users/new'
  get 'users/edit'

  get 'admin_pages/active_courses'
  get 'admin_pages/add_course'
  get 'admin_pages/delete_course'
  get 'admin_pages/edit_course'

  #get    '/contact',   to: 'contacts#new'
  #post   '/contact',   to: 'contacts#create'
  match '/contact', to: 'contacts#new', via: 'get'
  resources "contacts", only: [:new, :create]

  root 'static_pages#home'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Massage BGal House", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Inicio", root_path %></li>
        <li class="<%= 'active' if current_page?(courses_path) %>"><%= link_to "Cursos", courses_path %></li>
        <% if admin? %>
            <li class="<%= 'active' if current_page?(users_path) %>"><%= link_to "Usuarios", users_path %></li>
        <% end %>
        <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "Contactanos", contact_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Cuenta <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" id="DropdownMenu">
              <li><%= link_to "Profile", current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Cerrar sesión", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Iniciar sesión", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
      <strong align="center" style="color:red"><%= content_tag :div, value, class: "flash #{key}" %> </strong>
      <% end %>
      
      <%= yield %>
     
    </div>
  </body>
</html>